import {
  AccountChannels,
  AIChannels,
  AIStreamChannels,
  ProfileAccessChannels,
  CloudAuthChannels,
  DashboardChannels,
  DataPortabilityChannels,
  DesktopFeatureChannels,
  GoalChannels,
  NotificationChannels,
  RendererEventChannels,
  ReminderChannels,
  RoutineChannels,
  RepositoryChannels,
  ScheduleChannels,
  SettingChannels,
  SystemChannels,
  TaskChannels,
  WindowChannels,
} from '@memoflow/contracts/electron';
import { GovernanceChannels } from '@memoflow/contracts/governance';

export const SUPPORTED_REPOSITORY_CHANNELS = [
  RepositoryChannels.KNOWLEDGE_CONNECTION_INSTALLATION_START,
  RepositoryChannels.KNOWLEDGE_CONNECTION_INSTALLATION_COMPLETE,
  RepositoryChannels.KNOWLEDGE_CONNECTION_INSTALLATION_STATUS,
  RepositoryChannels.KNOWLEDGE_CONNECTION_INSTALLATION_FINALIZE,
  RepositoryChannels.KNOWLEDGE_CONNECTION_LIST,
  RepositoryChannels.KNOWLEDGE_CONNECTION_REFRESH_OBSERVATION,
  RepositoryChannels.KNOWLEDGE_CONNECTION_CONNECT,
  RepositoryChannels.KNOWLEDGE_CONNECTION_DISCONNECT,
  RepositoryChannels.KNOWLEDGE_CONNECTION_RECONCILIATION_PREVIEW,
  RepositoryChannels.KNOWLEDGE_CONNECTION_RECONCILIATION_EXECUTE,
  RepositoryChannels.KNOWLEDGE_CONNECTION_SYNC,
  RepositoryChannels.KNOWLEDGE_CONNECTION_DESKTOP_TOKEN,
  RepositoryChannels.KNOWLEDGE_WRITE_REQUEST_LIST,
  RepositoryChannels.KNOWLEDGE_WRITE_REQUEST_REPLAY,
  RepositoryChannels.LOCAL_VAULT_GET,
  RepositoryChannels.LOCAL_VAULT_SELECT,
  RepositoryChannels.LOCAL_VAULT_DETACH,
  RepositoryChannels.LOCAL_VAULT_SCAN,
  RepositoryChannels.LOCAL_VAULT_NOTE_READ,
  RepositoryChannels.LOCAL_VAULT_SEARCH,
  RepositoryChannels.LOCAL_VAULT_OPEN_OBSIDIAN,
  RepositoryChannels.LOCAL_VAULT_NOTE_WRITE_CONFIRMED,
] as const;

export const ALLOWED_CHANNELS = [
  ...Object.values(SystemChannels),
  ...Object.values(GoalChannels),
  ...Object.values(TaskChannels),
  ...Object.values(ScheduleChannels),
  ...Object.values(ReminderChannels),
  ...Object.values(RoutineChannels),
  ...Object.values(AccountChannels),
  ...Object.values(ProfileAccessChannels),
  ...Object.values(CloudAuthChannels),
  ...Object.values(DashboardChannels),
  ...Object.values(DesktopFeatureChannels),
  ...Object.values(RendererEventChannels),
  ...Object.values(NotificationChannels),
  ...SUPPORTED_REPOSITORY_CHANNELS,
  ...Object.values(SettingChannels),
  ...Object.values(WindowChannels),
  ...Object.values(GovernanceChannels),
  ...Object.values(AIChannels),
  ...Object.values(AIStreamChannels),
  ...Object.values(DataPortabilityChannels),
] as const;

export type AllowedIpcChannel = (typeof ALLOWED_CHANNELS)[number];
