<template>
  <section class="flex h-full min-h-0 flex-col overflow-hidden bg-background" data-testid="goal-detail-view">
    <header class="flex min-h-14 items-center gap-2 border-b px-4">
      <Button variant="ghost" size="sm" @click="router.push({ name: 'goal-list' })"><ArrowLeft class="mr-1 h-4 w-4"/>{{ t('common.back') }}</Button>
      <div v-if="goal" class="min-w-0"><h1 class="truncate font-semibold" data-testid="goal-detail-title">{{ goal.name }}</h1></div>
      <div v-if="goal" class="ml-auto flex flex-wrap justify-end gap-1">
        <template v-if="!goal.archivedAt">
          <Button v-if="goal.status === 'Planned'" size="sm" data-testid="goal-start-action" :disabled="isSaving" @click="activateGoal(String(goal.id))">{{ t('goal.detail.startGoal') }}</Button>
          <Button v-if="goal.status === 'InProgress'" variant="outline" size="sm" data-testid="goal-plan-action" :disabled="isSaving" @click="planGoal(String(goal.id))">{{ t('goal.detail.returnToPlan') }}</Button>
          <Button v-if="goal.status === 'InProgress'" size="sm" data-testid="goal-complete-action" :disabled="isSaving" @click="completeGoal(String(goal.id))">{{ t('goal.detail.completeGoal') }}</Button>
          <Button v-if="goal.status === 'Completed'" size="sm" data-testid="goal-reopen-action" :disabled="isSaving" @click="activateGoal(String(goal.id))">{{ t('goal.detail.reopenGoal') }}</Button>
          <Button v-if="goal.status === 'Abandoned'" variant="outline" size="sm" data-testid="goal-plan-action" :disabled="isSaving" @click="planGoal(String(goal.id))">{{ t('goal.detail.returnToPlan') }}</Button>
          <Button v-if="goal.status === 'Abandoned'" size="sm" data-testid="goal-resume-action" :disabled="isSaving" @click="activateGoal(String(goal.id))">{{ t('goal.detail.resumeGoal') }}</Button>
          <Button v-if="goal.status === 'Planned' || goal.status === 'InProgress'" variant="ghost" size="sm" class="text-destructive" data-testid="goal-abandon-action" :disabled="isSaving" @click="confirmAbandon">{{ t('goal.detail.abandonGoal') }}</Button>
        </template>
        <Button variant="ghost" size="sm" @click="openEdit">{{ t('common.edit') }}</Button>
        <Button size="sm" @click="openCreateKr">Add KR</Button>
        <Button variant="outline" size="sm" @click="router.push({ name: 'goal-review-create', params: { goalId: goal.id } })">Review</Button>
      </div>
    </header>
    <div v-if="isLoading" class="flex flex-1 items-center justify-center text-sm text-muted-foreground">{{ t('common.loading') }}</div>
    <div v-else-if="error" class="m-4 rounded-md border border-destructive/30 bg-destructive/5 p-4 text-sm text-destructive">{{ error }}</div>
    <div v-else-if="goal" class="min-h-0 flex-1 overflow-auto p-4"><div class="mx-auto max-w-4xl space-y-5">
      <article class="rounded-lg border bg-card p-5"><div class="flex flex-wrap items-center gap-2"><Badge>{{ goal.status }}</Badge><Badge v-if="goal.archivedAt" variant="outline">Archived</Badge><Badge v-for="label in goal.labels" :key="label.id" variant="secondary">{{ label.name }}</Badge></div><p v-if="goal.summary" class="mt-4 text-sm text-muted-foreground">{{ goal.summary }}</p><div class="mt-5"><div class="mb-1 flex justify-between text-sm"><span>Overall progress</span><span>{{ Math.round(goal.overallProgress) }}%</span></div><Progress :model-value="goal.overallProgress" /></div><dl class="mt-5 grid gap-4 text-sm sm:grid-cols-2"><div><dt class="text-muted-foreground">Start</dt><dd>{{ formatProductDate(goal.startDate, emptyNotSet(t)) }}</dd></div><div><dt class="text-muted-foreground">Due</dt><dd>{{ formatProductDate(goal.dueDate, emptyNotSet(t)) }}</dd></div></dl></article>
      <section class="space-y-3"><div class="flex items-center justify-between"><h2 class="font-medium">Key results</h2><span class="text-xs text-muted-foreground">{{ keyResults.length }}</span></div><div v-if="keyResults.length" class="space-y-2"><article v-for="kr in keyResults" :key="kr.id" class="rounded-lg border bg-card p-4"><button class="w-full text-left" @click="router.push({name:'key-result-detail',params:{goalId:goal.id,keyResultId:kr.id}})"><div class="flex justify-between gap-3"><div><h3 class="font-medium">{{ kr.title }}</h3><p v-if="kr.description" class="mt-1 text-sm text-muted-foreground">{{ kr.description }}</p></div><span class="text-sm font-medium">{{ Math.round(kr.progressPercentage) }}%</span></div><Progress class="mt-3" :model-value="kr.progressPercentage"/><div class="mt-2 flex gap-2 text-xs text-muted-foreground"><span>{{ kr.progress.currentValue }} / {{ kr.progress.targetValue }} {{ kr.progress.unit ?? '' }}</span><span>·</span><span>{{ kr.progress.aggregationMethod }}</span></div></button><div class="mt-3 flex justify-end gap-1"><Button variant="ghost" size="sm" @click="openEditKr(kr)">{{ t('common.edit') }}</Button><Button variant="ghost" size="sm" class="text-destructive" @click="removeKr(String(kr.id))">{{ t('common.delete') }}</Button></div></article></div><p v-else class="rounded-lg border border-dashed p-8 text-center text-sm text-muted-foreground">No key results yet.</p></section>
      <section class="space-y-3"><div class="flex items-center justify-between"><h2 class="font-medium">Reviews</h2><span class="text-xs text-muted-foreground">{{ goalReviews.length }}</span></div><button v-for="review in goalReviews" :key="review.id" class="block w-full rounded-lg border bg-card p-4 text-left" @click="router.push({name:'goal-review-detail',params:{goalId:goal.id,reviewId:review.id}})"><div class="flex justify-between gap-3"><p class="line-clamp-2 text-sm">{{ review.reflection }}</p><span class="shrink-0 text-xs text-muted-foreground">{{ formatProductDate(review.reviewedAt) }}</span></div><p class="mt-2 text-xs text-muted-foreground">{{ review.systemContext.overallProgress.startPercentage }}% → {{ review.systemContext.overallProgress.endPercentage }}% ({{ signed(review.systemContext.overallProgress.deltaPercentage) }})</p></button></section>
    </div></div>
    <GoalDialog v-model:open="editOpen" mode="edit" :goal="goal" @updated="reload"/>
    <KeyResultDialog ref="krDialog" :on-submit="saveKr" />
  </section>
</template>
<script setup lang="ts">
import { computed,onMounted,ref } from 'vue'; import { useRoute,useRouter } from 'vue-router'; import { useI18n } from 'vue-i18n'; import { ArrowLeft } from '@lucide/vue'; import { Badge,Button,Progress,useConfirm } from '@memoflow/ui-vue-shadcn'; import type { AddKeyResultReq, KeyResultClientDTO } from '@memoflow/contracts/goal'; import { GoalDialog,KeyResultDialog } from '../components'; import { emptyNotSet, formatProductDate } from '../../../shared/utils/product-time'; import { useGoal } from '../composables/useGoal';
type KeyResultInput = Omit<AddKeyResultReq, 'goalId' | 'expectedVersion'>;
const route=useRoute();const router=useRouter();const {t}=useI18n();const {selectedGoal:goal,keyResults,goalReviews,isLoading,isSaving,error,getGoalAggregateView,addKeyResult,updateKeyResult,deleteKeyResult,planGoal,activateGoal,completeGoal,abandonGoal}=useGoal();const goalId=computed(()=>String(route.params.id??''));const editOpen=ref(false);const krDialog=ref<InstanceType<typeof KeyResultDialog>|null>(null);async function reload(){await getGoalAggregateView(goalId.value);}onMounted(()=>void reload());function openEdit(){editOpen.value=true;}function openCreateKr(){krDialog.value?.openForCreateKeyResult(goalId.value);}function openEditKr(kr:KeyResultClientDTO){krDialog.value?.openForUpdateKeyResult(goalId.value,kr);}async function saveKr(payload:{goalId:string;keyResult:KeyResultInput;isEditing:boolean;keyResultId?:string}){const result=payload.isEditing&&payload.keyResultId?await updateKeyResult(payload.goalId,payload.keyResultId,payload.keyResult):await addKeyResult(payload.goalId,payload.keyResult);return !!result;}async function removeKr(id:string){if(await useConfirm({title:'Delete key result?',description:'This removes the measurement and its records.',confirmText:t('common.delete'),cancelText:t('common.cancel'),variant:'destructive'})){await deleteKeyResult(goalId.value,id);}}async function confirmAbandon(){if(!goal.value)return;if(await useConfirm({title:t('goal.detail.abandonGoal'),description:goal.value.name,confirmText:t('goal.detail.abandonGoal'),cancelText:t('common.cancel'),variant:'destructive'})){await abandonGoal(String(goal.value.id));}}
function signed(v:number){return `${v>=0?'+':''}${Math.round(v*100)/100}%`;}
</script>
